dist: xenial
addons:
  hosts:
    - api.localhost
language: node_js
node_js:
  - "12.4.0"
cache:
  directories:
    - node_modules
before_install:
  - sh create_credentials_js.sh
  - cat lib/credentials.js
install:
  - npm install
script:
  - npm run start &
  - sleep 10
  - npm run test